# Generated by Django 2.2.7 on 2019-12-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='', help_text='Slug will be generated automatically from the title of the post', unique=True),
        ),
    ]
